### ISSUE TITLE
Liverpool judies

### ISSUE THREAD

**Issue by CaptainSharks** [singaround/songbook#29]
https://www.auntieshanty.org/songs/liverpool-judies/

I don't really have a massive problem with this one - this suggests judies just means women: https://mudcat.org/thread.cfm?threadid=62354 ...
http://aliverpoolfolksongaweek.blogspot.com/2011/10/27-liverpool-judies.html
https://www.scousedictionary.co.uk/judy/

and the meaning is much like this one in Towrope Girls: 

Goodbye Serafina, Rosita and Luz,
The girls on the tow rope are steady and true,
Mothers and sisters and sweethearts and all,
It's haul away! All the way! Haul away haul!

So why not have these lyrics instead (more fun? No whorish deceit?) and just ditch the whore bit? Ok they wanted to escape Liverpool, so it doesn't really make sense that they'd be fondly thinking of Scouse girls, but I think it's not a massive deal...

From Liverpool to Frisco a-roving I went
To live in that country it was my intent;
But drinking strong liquor like other damned fools,
I soon got transported back to Liverpool.

Chorus (after each verse):
And it's row, row bullies row,
Them Liverpool judies has got us in tow.

I joined the ‘Alaska’ lying out in the bay,
A-waiting a fair wind to get under way.
Her crew was all weary, so sick and so sore, (so sick in the head?)
They'd had too much liquor and they'd had too much whore. (they wished they were dead?)

Then up stepped the mate in a hell of a stew,
Looking for work for the sailors to do.
“It's foretops'l halyards!” he loudly do roar,
“And lay aloft Paddy you son of an whore!”

One night off Cape Horn I shall never forget,
And oftimes I sighs when I thinks of it yet;
She were making twelve knots wi' her main skys'l set
And diving bows under with the whole of us wet.

We was hauling and pumping the whole bloody way,
By Jesus on that trip we sure earned our pay,
The mate was a cow-son, the bosun was worse,
With brass knuckles they added some weight to a curse.

Here's a health to Captain Samuels wherever he be,
A friend to a sailor on land or on sea,
But as the the first mate when his life do pass,
I hope that he hangs from the yard by his brass.

**Comment by CaptainSharks** [comment]
Aaaaaanyway I made a separate version, see what you reckon.

https://www.auntieshanty.org/admin/#/collections/song/entries/row-bullies-row-liverpool-judies-row-bullies-row-liverpool-judies

**Comment by RogerioY** [comment]
It's good! I reckon no one will be able to tell it's not traditional haha.

**Comment by singaround** [comment]
I've removed the original one and kept Rosie's. If we want the old one back, we can revert 8c965051e2a521f9a48b3f9b8cba7624325b3398
