### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by stevenpwilder** [singaround/songbook#76]
Master is chauvinist and does not fit the theme of Auntie Shanty

**Comment by RogerioY** [comment]
@singaround is this quite straightforward to do?

**Comment by stevenpwilder** [comment]
Yes, this is a good description https://www.git-tower.com/learn/git/faq/git-rename-master-to-main. It will require everyone to change their local checkout too.

**Comment by singaround** [comment]
Done!
